### ISSUE TITLE
We need a twitter account

### ISSUE THREAD

**Issue by mrtommyb** [dfm/sup#2]
I searched for a while to find anything appropriate. I registered @sendsup and @_supapp. Neither are that great but they were the best I could find.

Let's see if we can find something better.

**Comment by dfm** [comment]
I vote for therealsup

**Comment by dfm** [comment]
That was my plan for the domain too

**Comment by mrtommyb** [comment]
I registered @therealsup on twitter.

**Comment by dfm** [comment]
Gimme the password woudja. Also: http://therealsup.com/

**Comment by mrtommyb** [comment]
I've texted it to you.
